console.log('October 8th Very happy Starting React and doing my habits');
console.log('October 9th I had some errors doing my habits but I feel so happy');
console.log('October 10 hmmm regular day but I starting feel god because at least :D');
console.log('October 11 Very regular day but I spend time with my grandmother');
console.log('October 12 Full Work but I feel so sad for my status.');
console.log('October 13th I feel good with the return of my process good luck');
console.log('October 14th very so tired but lets go!');
console.log('October 15th Im very sad for my grandmother his feeling its very sad. but i trust in my god');
console.log('October 16th Thinking about my life in my future but also in the respect.');
console.log('October 17th A day very good but very less work but i feel blessed');
console.log('October 18th Idk :( good but...');
console.log('October 19th I dont have energy, i feel so tired but i want to improve but the lazy is very strong');
console.log('October 20th day of play football with my friends :D');
console.log('October 21th wtf idk it passing for my head!');
console.log('October 22th i dont know');
console.log('October 23th fun day with my friends but i did not work :(');
console.log('October 24th mt is doneeeeeeeeeeeeeeeeeeeeeeee. ');
console.log('October 25th maybe tired but i need following this path');
console.log('October 26th working in the game, lets go!');
console.log('October 27th tired but lets go with ingeniatec');
console.log('October 28th finishing the lab... the game');
console.log('October 29th a normal day but i feel tired! mttt')
console.log('October 30th great day in ingeniatec but I lost a opportunity with a girl very beautifull!! greattttt');
console.log('October 31th good day but its time to start the path');
console.log('November 1th fxck day, what is this shit?');
console.log('November 2th to 4th lets go with the process.....');
console.log('November 5th so sooooooooooo...');
console.log('November 6th I need to think things through...');
console.log('November 16th returning after 10 days');
console.log('November 18th time to change????????');
console.log('November 19th love not boy love not hahahaha');
console.log('November 20th hahaha trying new proyect');

