console.log('October 8th Very happy Starting React and doing my habits');
console.log('October 9th I had some errors doing my habits but I feel so happy');
console.log('October 10 hmmm regular day but I starting feel god because at least :D');
console.log('October 11 Very regular day but I spend time with my grandmother');
console.log('October 12 Full Work but I feel so sad for my status.');
console.log('October 13th I feel good with the return of my process good luck');
console.log('October 14th very so tired but lets go!');
console.log('October 15th Im very sad for my grandmother his feeling its very sad. but i trust in my god');
console.log('October 16th Thinking about my life in my future but also in the respect.');
console.log('October 17th A day very good but very less work but i feel blessed');
console.log('October 18th Idk :( good but...');